# Generated by Django 6.0.5 on 2026-06-19 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('DIRECTION', 'Direction'), ('SCOLARITE', 'Scolarité'), ('COMPTABILITE', 'Comptabilité'), ('INFORMATIQUE', 'Informatique'), ('SECRETARIAT', 'Secrétariat'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('MAINTENANCE', 'Maintenance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('position', models.CharField(max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contractuel'), ('INTERN', 'Stagiaire')], default='PERMANENT', max_length=20)),
                ('contract_hours_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.academicyear')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel administratif',
                'verbose_name_plural': 'Personnels administratifs',
                'db_table': 'staff_profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('IDENTITY', "Pièce d'identité"), ('CONTRACT', 'Contrat'), ('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='staff_documents/%Y/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
