# Generated by Django 5.0.1 on 2026-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Preuve de paiement'),
        ),
    ]
