# Generated by Django 5.0.1 on 2026-05-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0003_add_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Compte courant'), ('SAVINGS', 'Compte épargne'), ('PAYROLL', 'Compte salaires'), ('INVESTMENT', 'Investissement')], default='CHECKING', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('SALARY', 'Salaires'), ('INFRASTRUCTURE', 'Infrastructure'), ('SUPPLIES', 'Fournitures'), ('UTILITIES', 'Services (eau/élec)'), ('MAINTENANCE', 'Entretien'), ('MARKETING', 'Marketing'), ('TRANSPORT', 'Transport'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentmethod')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.site')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
