# Generated by Django 5.2.15 on 2026-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fix_fee_configuration_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='modality',
            field=models.CharField(blank=True, choices=[('PRESENTIEL', 'Présentiel'), ('ELEARNING', 'E-learning'), ('HYBRIDE', 'Hybride')], help_text='Laisser vide pour appliquer ce barème à toutes les modalités', max_length=20, null=True, verbose_name='Modalité'),
        ),
    ]
