# Generated by Django 5.2.15 on 2026-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_feeconfiguration_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='affectation_status',
            field=models.CharField(blank=True, choices=[('AFFECTE', 'Affecté (État)'), ('NON_AFFECTE', 'Non affecté (Privé)')], help_text='Laisser vide pour appliquer ce barème aux étudiants affectés et non affectés', max_length=20, null=True, verbose_name='Affectation'),
        ),
    ]
