# Generated by Django 5.2.15 on 2026-07-05 15:55
#
# Rewritten: the original auto-generated CreateModel let Django emit an
# inline CREATE TABLE ... FOREIGN KEY against fee_configurations(id).
# fee_configurations was force-converted to COLLATE=utf8mb4_0900_ai_ci by
# migration 0007 (see its docstring), but a fresh/empty database's default
# table collation (whatever MySQL server default is in effect) can differ
# from that — MySQL then refuses the FK with error 3780 ("Referencing
# column ... and referenced column ... are incompatible") and the whole
# CREATE TABLE is rolled back, so this migration never applies on such a
# database even though it had already applied fine, previously, against a
# database whose default happened to match. Explicitly declaring the same
# charset/collation as fee_configurations on this table makes it work
# regardless of the server's default collation.
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_feeconfiguration_affectation_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE `fee_installments` (
                        `id`                    char(32)        NOT NULL PRIMARY KEY,
                        `created_at`            datetime(6)     NOT NULL,
                        `updated_at`            datetime(6)     NOT NULL,
                        `is_active`             tinyint(1)      NOT NULL DEFAULT 1,
                        `label`                 varchar(100)    NOT NULL,
                        `due_date`              date            NOT NULL,
                        `amount`                decimal(12,2)   NOT NULL,
                        `order`                 integer unsigned NOT NULL DEFAULT 0,
                        `fee_configuration_id`  char(32)        NOT NULL,
                        CONSTRAINT `fee_installments_fee_configuration_id_9e071991_fk_fee_confi`
                            FOREIGN KEY (`fee_configuration_id`)
                            REFERENCES `fee_configurations` (`id`)
                            ON DELETE CASCADE
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS `fee_installments`;',
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX `fee_installments_fee_configuration_id_9e071991` ON `fee_installments` (`fee_configuration_id`);",
                    reverse_sql='',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FeeInstallment',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                        ('due_date', models.DateField(help_text='La tranche doit être soldée au plus tard 5 jours après cette date', verbose_name="Date d'échéance")),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                        ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                        ('fee_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.feeconfiguration', verbose_name='Barème')),
                    ],
                    options={
                        'verbose_name': 'Échéance',
                        'verbose_name_plural': 'Échéancier',
                        'db_table': 'fee_installments',
                        'ordering': ['order', 'due_date'],
                    },
                ),
            ],
        ),
    ]
