# Generated by Django 5.2.15 on 2026-07-05 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_feeconfiguration_affectation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('due_date', models.DateField(help_text='La tranche doit être soldée au plus tard 5 jours après cette date', verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('fee_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.feeconfiguration', verbose_name='Barème')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéancier',
                'db_table': 'fee_installments',
                'ordering': ['order', 'due_date'],
            },
        ),
    ]
