# Generated by Django 5.2.15 on 2026-07-11 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_feeconfiguration_remove_old_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='declared_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement déclarée'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro du payeur'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro destinataire'),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
    ]
