# Generated by Django 5.2.15 on 2026-07-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_merge_inscription_into_scolarite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconfiguration',
            name='fee_category',
            field=models.CharField(choices=[('INSCRIPTION', 'Inscription (historique)'), ('SCOLARITE', 'Scolarité')], default='SCOLARITE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
