# Generated by Django 5.2.15 on 2026-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_feeconfiguration_fee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='cycle',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('BTS1', 'BTS 1'), ('BTS2', 'BTS 2'), ('DUT1', 'DUT 1'), ('DUT2', 'DUT 2'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10, null=True, verbose_name='Cycle'),
        ),
    ]
