# Generated by Django 5.2.15 on 2026-07-05 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIKeywordResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('keyword', models.CharField(max_length=100)),
                ('question_example', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField()),
                ('priority', models.PositiveIntegerField(default=0, help_text='0 = priorité la plus haute')),
            ],
            options={
                'verbose_name': 'Réponse IA (mot-clé)',
                'verbose_name_plural': 'Réponses IA (mots-clés)',
                'db_table': 'landing_ai_keyword_responses',
                'ordering': ['priority', 'keyword'],
            },
        ),
    ]
