# Generated by Django 5.2.15 on 2026-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_parent_relationship_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modality',
            field=models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('ELEARNING', 'E-learning'), ('HYBRIDE', 'Hybride')], default='PRESENTIEL', help_text='Mode de suivi : présentiel, e-learning ou hybride', max_length=20),
        ),
    ]
