# Generated by Django 5.2.15 on 2026-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='affectation_status',
            field=models.CharField(choices=[('AFFECTE', 'Affecté (État)'), ('NON_AFFECTE', 'Non affecté (Privé)')], default='NON_AFFECTE', help_text="Affecté par l'État (orientation nationale) ou non affecté (admission privée)", max_length=20),
        ),
    ]
