# Generated by Django 5.2.15 on 2026-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_affectation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='echeance_override',
            field=models.BooleanField(default=False, help_text="Autorisation spéciale accordée par l'administration malgré un retard sur l'échéancier de scolarité"),
        ),
    ]
