# Generated by Django 5.2.15 on 2026-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_registration_fee_paid_is_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='elearning_access',
            field=models.BooleanField(default=True, help_text="Active/désactive l'accès de l'étudiant aux ressources e-learning (cours, examens, évaluations) — indépendant du statut de paiement, contrôlé directement par l'administration."),
        ),
    ]
