# Generated by Django 5.2.15 on 2026-07-04 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('app_name', models.CharField(default='CampusLMS', max_length=100)),
                ('app_subtitle', models.CharField(blank=True, default='Plateforme de gestion académique', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspace/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('font_size', models.PositiveSmallIntegerField(default=14)),
                ('compact_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('items_per_page', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Paramètres du workspace',
                'verbose_name_plural': 'Paramètres du workspace',
                'db_table': 'workspace_settings',
            },
        ),
    ]
