# Generated by Django 5.2.15 on 2026-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonattachment',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Bloc de contenu de leçon', 'verbose_name_plural': 'Blocs de contenu de leçons'},
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='block_type',
            field=models.CharField(choices=[('FILE', 'Fichier'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('TEXT', 'Texte'), ('HTML', 'HTML'), ('IFRAME', 'Iframe'), ('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo')], default='FILE', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/attachments/'),
        ),
    ]
