# Generated by Django 5.2.15 on 2026-06-28 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_session_semester'),
        ('elearning', '0004_lesson_min_duration_seconds_lesson_min_watch_percent_and_more'),
        ('students', '0004_parent_relationship_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('QCU', 'Choix unique'), ('QCM', 'Choix multiple'), ('TEXT', 'Texte libre'), ('NUMERIC', 'Calcul / Numérique'), ('MATCHING', 'Association'), ('ORDERING', 'Glisser-déposer (ordre)')], default='QCU', max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('explanation', models.TextField(blank=True)),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('numeric_tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('text_answer', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'db_table': 'quiz_questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('match_text', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='elearning.question')),
            ],
            options={
                'verbose_name': 'Choix de question',
                'verbose_name_plural': 'Choix de questions',
                'db_table': 'quiz_choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=0)),
                ('pass_score_percent', models.PositiveSmallIntegerField(default=50)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='academic.class')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='elearning.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'db_table': 'quizzes',
                'ordering': ['class_obj', 'subject', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elearning.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='elearning.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text_response', models.TextField(blank=True)),
                ('numeric_response', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ordering_response', models.JSONField(blank=True, default=list)),
                ('matching_response', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('manual_feedback', models.TextField(blank=True)),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='elearning.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.quizattempt')),
            ],
            options={
                'verbose_name': 'Réponse de tentative',
                'verbose_name_plural': 'Réponses de tentatives',
                'db_table': 'quiz_attempt_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
