# Generated by Django 5.2.15 on 2026-06-30 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_lot9_videos_lot8_classrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='exam_snapshots/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('face_detected', models.BooleanField(blank=True, null=True)),
                ('phone_detected', models.BooleanField(default=False)),
                ('ai_analysis', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='elearning.examsession')),
            ],
            options={
                'verbose_name': 'Capture webcam',
                'verbose_name_plural': 'Captures webcam',
                'db_table': 'exam_snapshots',
                'ordering': ['-taken_at'],
            },
        ),
    ]
