# Generated by Django 5.2.15 on 2026-06-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('elearning', '0008_lot12_exam_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site auquel ce document est rattaché. Laisser vide pour le rendre visible sur tous les sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_documents', to='core.site'),
        ),
    ]
