# Generated by Django 5.2.15 on 2026-07-01 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('elearning', '0009_librarydocument_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chapitre de cours',
                'verbose_name_plural': 'Chapitres de cours',
                'db_table': 'course_chapters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('all_levels', 'Tous niveaux')], default='all_levels', max_length=20)),
                ('language', models.CharField(default='Français', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('target_audience', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('what_you_will_learn', models.JSONField(blank=True, default=list)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.site')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio'), ('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('word', 'Word'), ('image', 'Image'), ('text', 'Texte'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('iframe', 'Iframe'), ('html5', 'HTML5')], default='video', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_preview_free', models.BooleanField(default=False)),
                ('download_allowed', models.BooleanField(default=False)),
                ('text_content', models.TextField(blank=True)),
                ('external_embed_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='courses/documents/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='elearning.coursechapter')),
            ],
            options={
                'verbose_name': 'Leçon de cours',
                'verbose_name_plural': 'Leçons de cours',
                'db_table': 'course_lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='elearning.course')),
            ],
            options={
                'verbose_name': 'Section de cours',
                'verbose_name_plural': 'Sections de cours',
                'db_table': 'course_sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='elearning.coursesection'),
        ),
    ]
