# Generated by Django 5.2.15 on 2026-07-02 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_assignment_online_exercises'),
        ('students', '0005_student_modality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField()),
                ('meeting_url', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('virtual_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='elearning.virtualclassroom')),
            ],
            options={
                'verbose_name': 'Segment de réunion',
                'verbose_name_plural': 'Segments de réunion',
                'db_table': 'meeting_segments',
                'ordering': ['sequence'],
                'unique_together': {('virtual_class', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log_type', models.CharField(choices=[('CREATED', 'Réunion créée'), ('STARTED', 'Réunion démarrée'), ('ENDED', 'Réunion terminée'), ('NOTIF_10MIN', 'Notification 10 min'), ('NOTIF_5MIN', 'Notification 5 min'), ('NOTIF_1MIN', 'Notification 1 min'), ('NOTIF_NEXT', 'Notification session suivante'), ('JOINED', 'Participant rejoint'), ('LEFT', 'Participant parti'), ('TRANSITION', 'Transition de session'), ('INCIDENT', 'Incident')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='elearning.meetingsegment')),
                ('virtual_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='elearning.virtualclassroom')),
            ],
            options={
                'verbose_name': 'Journal de session',
                'verbose_name_plural': 'Journaux de session',
                'db_table': 'session_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_duration', models.PositiveIntegerField(default=0)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='elearning.meetingsegment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to='students.student')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'session_participants',
                'unique_together': {('segment', 'student')},
            },
        ),
    ]
