# Generated by Django 5.2.15 on 2026-07-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_meeting_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='elearning.quiz'),
        ),
    ]
