# Generated by Django 5.2.15 on 2026-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_course_quiz_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL vidéo de présentation (YouTube, Vimeo…)'),
        ),
    ]
