# Generated by Django 5.2.15 on 2026-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_exam_session_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='pdf_extra_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
