# Generated by Django 5.2.15 on 2026-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_session_semester'),
        ('elearning', '0018_add_pdf_extra_duration_to_secure_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureexam',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_exams', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='secureexam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_exams', to='academic.subject'),
        ),
        migrations.AlterField(
            model_name='secureexam',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
