# Generated by Django 5.2.15 on 2026-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0019_secure_exam_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureexam',
            name='max_tab_switches',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
