# Generated by Django 5.2.15 on 2026-07-04 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_alter_secureexam_max_tab_switches'),
        ('students', '0005_student_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='elearning.courselesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_progress', to='students.student')),
            ],
            options={
                'verbose_name': 'Progression de leçon de cours',
                'verbose_name_plural': 'Progressions de leçons de cours',
                'db_table': 'course_lesson_progress',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
