# Generated by Django 5.2.15 on 2026-07-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0021_courselessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='fraud_block_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
