# Generated by Django 5.2.15 on 2026-07-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_level_cycle_swap'),
        ('core', '0002_workspacesettings'),
        ('elearning', '0022_examsession_fraud_block_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualclassroom',
            name='is_spontaneous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualclassroom',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_classrooms', to='core.site'),
        ),
        migrations.AlterField(
            model_name='virtualclassroom',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_classrooms', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='virtualclassroom',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_classrooms', to='academic.subject'),
        ),
    ]
