# Generated by Django 5.2.15 on 2026-07-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspacesettings'),
        ('elearning', '0023_virtualclassroom_is_spontaneous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secureexam',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_secure_exams', to='core.site'),
        ),
    ]
