# Generated by Django 5.2.15 on 2026-07-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_level_cycle_swap'),
        ('elearning', '0024_secureexam_is_global_secureexam_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='academic.subject'),
        ),
    ]
