# Generated by Django 5.2.15 on 2026-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0025_alter_quiz_class_obj_alter_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_prompt',
            field=models.TextField(blank=True),
        ),
    ]
