# Generated by Django 5.2.15 on 2026-07-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_level_cycle_swap'),
        ('elearning', '0026_question_question_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_exams', to='academic.teacherprofile'),
        ),
    ]
