# Generated by Django 5.2.15 on 2026-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0027_secureexam_teacher'),
        ('students', '0009_student_elearning_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='targeted_secure_exams', to='students.student'),
        ),
    ]
