# Generated by Django 5.2.15 on 2026-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0028_secureexam_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='device_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='examsession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
