# Generated by Django 5.2.15 on 2026-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0029_examsession_device_token_examsession_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='restrict_to_selected_students',
            field=models.BooleanField(default=False),
        ),
    ]
