# Generated by Django 5.2.15 on 2026-08-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0030_secureexam_restrict_to_selected_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
