# Generated by Django 5.2.15 on 2026-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0031_secureexam_break_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='break_interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
