# Generated by Django 5.2.15 on 2026-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0032_secureexam_break_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexam',
            name='gaze_away_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
