# Generated by Django 5.0.1 on 2026-02-07 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinetPayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=255)),
                ('cinetpay_site_id', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=255)),
                ('notify_url', models.URLField()),
                ('return_url', models.URLField(blank=True)),
                ('cancel_url', models.URLField(blank=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_config', to='core.site')),
            ],
            options={
                'verbose_name': 'Configuration CinetPay',
                'verbose_name_plural': 'Configurations CinetPay',
                'db_table': 'cinetpay_configs',
            },
        ),
        migrations.CreateModel(
            name='CinetPayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('cinetpay_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_url', models.URLField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('operator_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_cinetpay_transactions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinetpay_transactions', to='finance.invoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinetpay_transaction', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Transaction CinetPay',
                'verbose_name_plural': 'Transactions CinetPay',
                'db_table': 'cinetpay_transactions',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
