# Generated by Django 5.0.1 on 2026-05-18 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academic.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Matière par niveau',
                'verbose_name_plural': 'Matières par niveau',
                'db_table': 'level_subjects',
                'ordering': ['subject__name'],
                'unique_together': {('level', 'subject')},
            },
        ),
    ]
