# Generated by Django 6.0.5 on 2026-06-19 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_room_gps'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contract_hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('IDENTITY', "Pièce d'identité"), ('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='teacher_documents/%Y/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.teacherprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_teacher_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document enseignant',
                'verbose_name_plural': 'Documents enseignants',
                'db_table': 'teacher_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
