# Generated by Django 6.0.5 on 2026-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_session_postponement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='student_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
