# Generated by Django 5.2.15 on 2026-07-05 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0008_session_semester'),
        ('students', '0005_student_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentKPIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='LOW', max_length=10)),
                ('kpi_snapshot', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_tokens_used', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_analyses', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_analyses', to='students.student')),
            ],
            options={
                'verbose_name': 'Analyse KPI étudiant',
                'verbose_name_plural': 'Analyses KPI étudiant',
                'db_table': 'student_kpi_analyses',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
