# Generated by Django 5.0.1 on 2026-05-19 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('PAYMENT_VALIDATED', 'Paiement validé'), ('ABSENCE_RECORDED', 'Absence constatée'), ('ABSENCE_PLANNED', 'Absence prévue'), ('CASH_DEPOSIT', 'Versement caisse'), ('MOBILE_MONEY', 'Mobile money'), ('GRADE_PUBLISHED', 'Note publiée'), ('BULLETIN_PUBLISHED', 'Bulletin publié'), ('CUSTOM', 'Personnalisé')], max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push'), ('IN_APP', 'In-App')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Sujet email ou titre push', max_length=255)),
                ('body', models.TextField(help_text='Variables: {{student_name}}, {{amount}}, {{date}}, {{subject_name}}')),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['event_type', 'channel'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_address',
            field=models.CharField(blank=True, help_text='email / phone / device token', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement'), ('ATTENDANCE', 'Présence'), ('ABSENCE', 'Absence'), ('ASSIGNMENT', 'Devoir'), ('GRADE', 'Note'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système'), ('REMINDER', 'Rappel'), ('ALERT', 'Alerte'), ('FINANCE', 'Finance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp'), ('WEBSOCKET', 'WebSocket')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('DELIVERED', 'Délivré'), ('FAILED', 'Échoué'), ('RETRYING', 'Relance')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_44e75a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_d7ad6a_idx'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_templates', to='core.site'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('event_type', 'channel', 'site')},
        ),
    ]
