# Generated by Django 5.2.15 on 2026-07-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_devicetoken_unique_user_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='is_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
