# Generated by Django 5.2.15 on 2026-07-17 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_session_semester'),
        ('core', '0002_workspacesettings'),
        ('notifications', '0005_devicetoken_is_logged_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_type', models.CharField(choices=[('ECHEANCIER', 'Échéancier'), ('EXAMEN', 'Examen')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_automatic', models.BooleanField(default=True)),
                ('echeancier_start_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('echeancier_frequency_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('echeancier_deadline_date', models.DateField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_reminder_frequency_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_configs', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_configs', to='academic.level')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_configs', to='academic.program')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_configs', to='core.site')),
            ],
            options={
                'db_table': 'reminder_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
