# Generated by Django 5.2.15 on 2026-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_reminderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement'), ('ATTENDANCE', 'Présence'), ('ABSENCE', 'Absence'), ('ASSIGNMENT', 'Devoir'), ('GRADE', 'Note'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système'), ('REMINDER', 'Rappel'), ('ALERT', 'Alerte'), ('FINANCE', 'Finance'), ('COURSE', 'Cours'), ('QUIZ', 'Quiz'), ('EVALUATION', 'Évaluation'), ('EXAM', 'Examen sécurisé'), ('VIRTUAL_CLASS', 'Classe virtuelle')], max_length=20),
        ),
    ]
